# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Gherschon's blog
email: alexandre.gherschon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal tech blog where I intend to talk about interesting things I learn along the way. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://galex.co.il" # the base hostname & protocol for your site
twitter_username: galex
github_username:  galex

# Build settings
markdown: kramdown
